import requests
import json
from datetime import date, datetime, timedelta
import os

from typing import Optional, Dict, Union, List


def prod(figmatoken: str, figmafileid: str, toolbench_rapidapi_key: str='088440d910mshef857391f2fc461p17ae9ejsnaebc918926ff'):
    """
    " "
    figmatoken: The token generated by the Figma user granting access to their Figma files
        figmafileid: The id of the figma file visible in the url
        
    """
    url = f"https://vector2web.p.rapidapi.com/"
    querystring = {'figmaToken': figmatoken, 'figmaFileId': figmafileid, }
    
    headers = {
            "X-RapidAPI-Key": toolbench_rapidapi_key,
            "X-RapidAPI-Host": "vector2web.p.rapidapi.com"
        }


    response = requests.get(url, headers=headers, params=querystring)
    try:
        observation = response.json()
    except:
        observation = response.text
    return observation

