?start: functioncall
    ?functioncall: name "(" args ")" "="
    name: "add" | "subtract" | "multiply" | "divide" | "power" | "sqrt" | "log" | "ln" | "choose" | "permutate" | "gcd" | "lcm" | "remainder"
    args: arg ("," arg)*
    arg: value | functioncall
    value: INT+ | INT+ "." INT+

    %import common.STRING
    %import common.SIGNED_NUMBER
    %import common.DIGIT
    %import common.INT
    %import common.WS
    %ignore WS