import requests
import json
from datetime import date, datetime, timedelta
import os

from typing import Optional, Dict, Union, List


def ip_city(ip: str, key: str, toolbench_rapidapi_key: str='088440d910mshef857391f2fc461p17ae9ejsnaebc918926ff'):
    """
    "Get the detail of Longitude and Latitude on the basis of IP-Address"
    ip: IP-Address of the Country
        key: API Key Generated by Infodb.com
        
    """
    url = f"https://sanarora-get-ip-info.p.rapidapi.com/v3/ip-city/"
    querystring = {'ip': ip, 'key': key, }
    
    headers = {
            "X-RapidAPI-Key": toolbench_rapidapi_key,
            "X-RapidAPI-Host": "sanarora-get-ip-info.p.rapidapi.com"
        }


    response = requests.get(url, headers=headers, params=querystring)
    try:
        observation = response.json()
    except:
        observation = response.text
    return observation

