import requests
import json
from datetime import date, datetime, timedelta
import os

from typing import Optional, Dict, Union, List


def generate_a_face(ai: str, toolbench_rapidapi_key: str='088440d910mshef857391f2fc461p17ae9ejsnaebc918926ff'):
    """
    "Provides a link to download a face image generated by artificial intelligence.
		
		```
		
		Occasionally, a neural network makes mistakes, 
		which is why artifacts appear: an incorrectly bent pattern, 
		a strange hair color, and so on.
		```"
    
    """
    url = f"https://facegen.p.rapidapi.com/fg/"
    querystring = {'AI': ai, }
    
    headers = {
            "X-RapidAPI-Key": toolbench_rapidapi_key,
            "X-RapidAPI-Host": "facegen.p.rapidapi.com"
        }


    response = requests.get(url, headers=headers, params=querystring)
    try:
        observation = response.json()
    except:
        observation = response.text
    return observation

