import requests
import json
from datetime import date, datetime, timedelta
import os

from typing import Optional, Dict, Union, List


def get_all_urls(toolbench_rapidapi_key: str='088440d910mshef857391f2fc461p17ae9ejsnaebc918926ff'):
    """
    "`longUrl` =  URL provided by user
		`shortIdentity` = unique id created by API
		`shortUrl` = URL created by server
		( `_id `, ` date` and `_v` are fields generated by server)"
    
    """
    url = f"https://url-shortner10.p.rapidapi.com/lits.rocks/"
    querystring = {}
    
    headers = {
            "X-RapidAPI-Key": toolbench_rapidapi_key,
            "X-RapidAPI-Host": "url-shortner10.p.rapidapi.com"
        }


    response = requests.get(url, headers=headers, params=querystring)
    try:
        observation = response.json()
    except:
        observation = response.text
    return observation

