import requests
import json
from datetime import date, datetime, timedelta
import os

from typing import Optional, Dict, Union, List


def api_vcodes_api_php_siteid_siteid(siteid: str, toolbench_rapidapi_key: str='088440d910mshef857391f2fc461p17ae9ejsnaebc918926ff'):
    """
    "Free Coupon Codes"
    siteid: Site ID generated by Cashnjoy.com on registration. This identifies and attributes the transaction to particular website
        
    """
    url = f"https://cashnjoy-com-free-coupon-codes-v1.p.rapidapi.com/api/vcodes-api.php?siteid={siteid}"
    querystring = {}
    
    headers = {
            "X-RapidAPI-Key": toolbench_rapidapi_key,
            "X-RapidAPI-Host": "cashnjoy-com-free-coupon-codes-v1.p.rapidapi.com"
        }


    response = requests.get(url, headers=headers, params=querystring)
    try:
        observation = response.json()
    except:
        observation = response.text
    return observation

